source "https://rubygems.org"

gem 'thin'
gem 'sinatra'
gem 'rake'
gem 'sqlite3'

gem 'rspec'
gem 'activerecord', '4.1.9'
gem 'factory_girl', '4.0'
gem 'faker', '1.4.3'
gem 'database_cleaner', '1.4.0'