test:
  adapter: sqlite3
  database: ':memory:'
  pool: 20
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 20
  timeout: 5000
 
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 20
  timeout: 5000